name: Build and Release

# Trigger on push to main branch or manual trigger
on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual trigger from GitHub UI

permissions:
  contents: write  # Ensure that the workflow has write permissions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js environment for npm
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Updated to Node.js version 20

      # Install npm dependencies
      - name: Install dependencies
        working-directory: ./web
        run: npm install

      # Build the project
      - name: Build project
        working-directory: ./web
        run: npm run build

      # Create a new copy of the repository
      - name: Create new repository copy
        run: |
          # Create a new directory for the new repository copy
          NEW_REPO_DIR="./new_repo"
          mkdir -p $NEW_REPO_DIR

          # Copy the entire repository into the new directory
          rsync -av --exclude='.git/' --exclude='node_modules/' ./ $NEW_REPO_DIR/

          # Move the dist folder into the new web directory
          cp -r ./web/dist $NEW_REPO_DIR/web/  # Copy dist to the new web directory

      # Create a zip file of the new repository
      - name: Create zip file
        run: |
          cd ./new_repo
          zip -r ../new_repo.zip .  # Zip all contents in the new repository folder
          cd ..  # Go back to the root directory

      # Delete previous release if it exists
      - name: Delete previous release
        id: delete_release
        run: |
          # Get the latest release name and tag
          LATEST_RELEASE=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/releases/latest)

          # Extract tag name
          TAG_NAME=$(echo $LATEST_RELEASE | jq -r .tag_name)

          # Check if a release exists
          if [ "$TAG_NAME" != "null" ]; then
            echo "Deleting release with tag: $TAG_NAME"
            curl -s -X DELETE -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              https://api.github.com/repos/${{ github.repository }}/releases/$TAG_NAME

            # Delete the corresponding tag
            git push --delete origin $TAG_NAME
          else
            echo "No previous release found."
          fi

      # Get the commit message for the release name
      - name: Get commit message
        id: get_commit_message
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          echo "Release name: $COMMIT_MESSAGE"
          echo "RELEASE_NAME=$COMMIT_MESSAGE" >> $GITHUB_ENV

      # Create a new release with tag "latest"
      - name: Create a Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "latest"  # Set tag name to "latest"
          release_name: ${{ env.RELEASE_NAME }}  # Use the commit message as the release name
          body: |
            Automatically generated release based on the push
          draft: false
          prerelease: false

      # Upload the built artifacts to the release
      - name: Upload Build Artifacts to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./new_repo.zip  # The zip file we just created
          asset_name: new_repo.zip
          asset_content_type: application/zip
