name: Build and Release

# Trigger on push to main branch or manual trigger
on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual trigger from GitHub UI

permissions:
  contents: write  # Ensure that the workflow has write permissions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js environment for npm
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # or any other Node.js version you need

      # Install npm dependencies
      - name: Install dependencies
        working-directory: ./web
        run: npm install

      # Build the project
      - name: Build project
        working-directory: ./web
        run: npm run build

      # Get the latest release tag
      - name: Get latest release
        id: get_latest_release
        run: |
          TAG=$(git tag | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' | sort -V | tail -n 1)
          echo "Latest tag: $TAG"
          if [ -z "$TAG" ]; then
            TAG="v1.0.0"  # Start with v1.0.0 if no tags exist
          fi
          echo "TAG=$TAG" >> $GITHUB_ENV

      # Increment the version
      - name: Increment version
        id: increment_version
        run: |
          # Remove the 'v' and split the version into parts
          IFS='.' read -r major minor patch <<< "${TAG:1}"
          patch=$((patch + 1))  # Increment the patch version
          NEW_TAG="v${major}.${minor}.${patch}"
          echo "New tag: $NEW_TAG"
          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV

      # Create a zip file of the built artifacts
      - name: Create zip file
        run: |
          cd ./web/dist
          zip -r ../dist.zip .  # Create a zip file containing all files in dist
          cd ../../  # Go back to the root directory

      # Create a release
      - name: Create a Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.NEW_TAG }}  # Use the new incremented tag
          release_name: Release ${{ env.NEW_TAG }}
          body: |
            Automatically generated release based on the push
          draft: false
          prerelease: false

      # Upload the built artifacts to the release
      - name: Upload Build Artifacts to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./web/dist.zip  # The zip file we just created
          asset_name: dist.zip
          asset_content_type: application/zip
