name: Build and Release

# Trigger on push to main branch or manual trigger
on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual trigger from GitHub UI

permissions:
  contents: write  # Ensure that the workflow has write permissions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        working-directory: ./web
        run: npm install

      - name: Build project
        working-directory: ./web
        run: npm run build

      # Create a release
      - name: Create a Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.sha }}
          release_name: Release ${{ github.sha }}
          body: |
            Automatically generated release based on the push
          draft: false
          prerelease: false

      # Upload the built artifacts to the release
      - name: Upload Build Artifacts to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./web/dist/
          asset_name: ragemenu.zip
          asset_content_type: application/zip
